### ISSUE TITLE
[Bug]: Crash on Startup: NoClassDefFoundError (spectrelib)

### ISSUE THREAD

**Issue by DeshiDesu** [TheIllusiveC4/Comforts#130]
### Minecraft Version

1.19.2

### What happened?

Client crashes on initialization with comforts installed:

```
java.lang.NoClassDefFoundError: net/fabricmc/loader/impl/entrypoint/EntrypointUtils
	at com.illusivesoulworks.spectrelib.SpectreClientFabricMod.prepareConfigs(SpectreClientFabricMod.java:57)
	at net.minecraft.class_310.handler$zke000$spectrelib$init(class_310.java:5965)
	at net.minecraft.class_310.<init>(class_310.java:456)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.loader.impl.entrypoint.EntrypointUtils
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

### How do you trigger this bug?

1. Install Comforts in a new instance
2. Launch
3. Crash

### Loader

Fabric

### Loader Version

Fabric 0.14.23

### API Version

fabric-api-0.76.1+1.19.2

### Mod Version

comforts-fabric-6.0.4+1.19.2

### Relevant Log Outputs

[latest.log](https://github.com/illusivesoulworks/comforts/files/12833901/latest.log)
[crash-2023-10-06_13.37.40-client.txt](https://github.com/illusivesoulworks/comforts/files/12833902/crash-2023-10-06_13.37.40-client.txt)

**Comment by averycoolbean** [comment]
i have found the weirdest behaviour in that it works in our larger modpack (for the most part doesnt crash on its own but the same error appears upon a different mod causing a crash)

same behaviour in isolation but apparently if you mod the game enough it magically starts working again, havent figured out what mod or combination of mods did it though

**Comment by Poopooracoocoo** [comment]
As a workaround, you can downgrade Fabric Loader to 0.14.22

Also see https://github.com/illusivesoulworks/spectrelib/issues/3

**Comment by user10072023github** [comment]
Can confirm crash occurs on 1.19.4 also (with version 6.2.0 of this mod) showing same error as op.  Sticking with my 1.19.4 for a long time so I really ope this can get resolved and happy to help if I can.  Thanks so much

**Comment by user10072023github** [comment]
Confirming this crash is fixed!  Thanks so much TheIllusiveC4

**Comment by Cape-City** [comment]
Same Issue, only within 1.19.3 and there is actually no fix available :( Will the 1.19.3 Version of this mod also get this fix?
For now i have to deactivate this mod, 'coz there are too many which needs the Fabric Version 0.15+ which i can't update,
if letting this mod within my modpack.

**Comment by Poopooracoocoo** [comment]
@Cape-City Download the 1.19.x release of SpectreLib: https://github.com/illusivesoulworks/spectrelib/releases

**Comment by Cape-City** [comment]
> @Cape-City Download the 1.19.x release of SpectreLib: https://github.com/illusivesoulworks/spectrelib/releases

Works perfect now, but it is ok, having the spectrelib in my curseforge modpack, 'coz i can't find it in the CF library and have to put it manually into the pack.
