### ISSUE TITLE
Server crash with 1.3.1 + Forge 2784

### ISSUE THREAD

**Issue by mr2013** [TheIllusiveC4/Comforts#22]
Transcription of crash below. Full log located at https://pastebin.com/rHbzCihH Full mod list located at https://pastebin.com/aEtpbcJg Server specs are docker container running on Ubuntu 18.04.1 LTS with 24 gigs of ram dedicated to process. Removing comforts allows server to run successfully.

> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: java.lang.NegativeArraySizeException
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at org.objectweb.asm.Frame.a(Unknown Source)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at c4.comforts.asm.SleepTransformer.transform(SleepTransformer.java:104)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at c4.comforts.asm.SleepTransformer.transformPlayerSleep(SleepTransformer.java:67)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at c4.comforts.asm.SleepTransformer.transform(SleepTransformer.java:52)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
> [02:52:55] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:709]:     ... 17 more

**Comment by TheIllusiveC4** [comment]
Yeah this is due to some changes in Forge version 2776. You'll have to use a version before that. I'm working on a quick fix that should be out by sometime tomorrow that will be compatible with the newer Forge versions.
