### ISSUE TITLE
Game crashes when I break a sleeping bag

### ISSUE THREAD

**Issue by kaiden-lcfc** [TheIllusiveC4/Comforts#76]
[crash-2022-03-08_15.56.14-server.txt](https://github.com/TheIllusiveC4/Comforts/files/8207746/crash-2022-03-08_15.56.14-server.txt)
Crash report ^

So i have placed a sleeping bag and slept however when trying to pick it back up, the game just crashes. I reopen the game and the sleeping bag is still there and its in the way so how can i break it or fix the bug?

Thanks :)

**Comment by TheIllusiveC4** [comment]
Update to the latest Comforts (1.18.2-5.0.0.3) and let me know if it's still an issue.

**Comment by jupiter-august** [comment]
Same issue, current version. Now my world won't load after the crash.

**Comment by TheIllusiveC4** [comment]
Strange then, I can't reproduce your issue. Can you share the crash log with the current version?

**Comment by kaiden-lcfc** [comment]
> Update to the latest Comforts (1.18.2-5.0.0.3) and let me know if it's still an issue.

Thanks that fixed it, i tried to unscramble the logs myself to see what the problem was but i could make any sense of it so thanks for the help :)

**Comment by kuehnfelix** [comment]
Same problem for me. Using `comforts-forge-1.18.2-5.0.0.3 ` with forge `39.1.2`. Trying to destroy a sleeping bag on a server produces the following exception for the client trying to break it as well as for the server:

<details>
  <summary>[16:11:19] [Server thread/ERROR]: Encountered an unexpected exception...</summary>
  
```
[16:11:19] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: f_13088_
	at top.theillusivec4.comforts.common.block.ComfortsBaseBlock.m_5707_(ComfortsBaseBlock.java:278) ~[comforts-forge-1.18.2-5.0.0.3.jar%2348!/:task ':jar' property 'archiveVersion']
	at net.minecraftforge.common.extensions.IForgeBlock.onDestroyedByPlayer(IForgeBlock.java:179) ~[forge-1.18.1-39.0.89-universal.jar%2375!/:?]
	at net.minecraftforge.common.extensions.IForgeBlockState.onDestroyedByPlayer(IForgeBlockState.java:136) ~[forge-1.18.1-39.0.89-universal.jar%2375!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.removeBlock(ServerPlayerGameMode.java:268) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9280_(ServerPlayerGameMode.java:251) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_9286_(ServerPlayerGameMode.java:217) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7391_(ServerPlayerGameMode.java:187) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7502_(ServerGamePacketListenerImpl.java:945) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:34) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.m_5797_(ServerboundPlayerActionPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2371!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Ultimaheart4** [comment]
comforts version, 1.18.2-5.0.0.3, i am also having the same issue with my server and sometimes only client crashing when breaking a sleeping bag after placed when trying to sleep before night, it also doesnt auto pick up after sleeping in it, ive had to use world edit to remove the sleeping bags from the world
[crash-2022-03-08_19.19.49-client.txt](https://github.com/TheIllusiveC4/Comforts/files/8217053/crash-2022-03-08_19.19.49-client.txt)
[crash-2022-03-08_19.19.47-server.txt](https://github.com/TheIllusiveC4/Comforts/files/8217060/crash-2022-03-08_19.19.47-server.txt)

.
if it helps we are using minecolonies, but only once did it crash when using (breaking after it gets stuck on the ground) the sleeping bag inside the minecolonies borders. the rest have been outside.

**Comment by TheIllusiveC4** [comment]
Okay, I think everyone is having the same issue, which is that you're using versions that don't match your Minecraft version. That was my bad, because it was not marked correctly. To solve the issue:

1. If you're on 1.18.1, only use up to Comforts 1.18.1-5.0.0.2. Do not update past that unless you update to Minecraft 1.18.2.
2. If you're on 1.18.2, only use Comforts 1.18.2-5.0.0.3 or later.

If you're still having crashes despite the fact that your versions match, please report back with the crash log.
