### ISSUE TITLE
1.18.1 Fabric - Parsing error loading recipe comforts:rope_and_nail_shapeless - Unknown item tag 'c:rope'

### ISSUE THREAD

**Issue by davidalb97** [TheIllusiveC4/Comforts#77]
#### Versions (Be specific, do not write "latest"):
* Comforts: 1.0.3
* Forge/Fabric: 0.46.6
* Minecraft: 1.18.1
* Fabric Loader: 0.13.3

#### Observed Behavior:
```
[Worker-Main-30/ERROR]: Parsing error loading recipe comforts:rope_and_nail_shapeless
com.google.gson.JsonSyntaxException: Unknown item tag 'c:rope'
        at net.minecraft.class_1856.method_17873(class_1856.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.class_5415.method_33166(class_5415.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.class_1856.method_8107(class_1856.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.class_1867$class_1868.method_8144(class_1867.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:83) ~[server-intermediary.jar:?]
        at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[server-intermediary.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[server-intermediary.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[server-intermediary.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```
#### Expected Behavior:
No error in the log.
#### Steps to Reproduce:
1.Create a minecraft server with 0.13.3 fabric loader for MC 1.18.1.
2. Install Conforts 1.0.3 & fabric api 0.46.6.
3.Watch the log before world generation.

Crash/Debug Logs: https://pastebin.com/UKqG5LYB

**Comment by TheIllusiveC4** [comment]
This should be fixed already in 1.18.2, but unfortunately won't be fixed in 1.18.1 as I am no longer making updates for that version. 

You can safely ignore it, it's only used in a recipe that is not functional unless a modpack developer adds items into the `c:rope` tag themselves. And if they do so, the error will fix itself anyways.

If it really bothers you for some reason and you are not using Haema (the 1.0.3 update fixed a major compatibility issue with that mod), then you can also safely downgrade to 1.0.2 as the other changes in 1.0.3 were not major.
